select sysdate from dual;

--PREGUNTA 1-3
select EMPLOYEE_ID, LAST_NAME, SALARY + (SALARY * 0.15) "NEW SALARY", 
SALARY * 0.15 INCREASE FROM EMPLOYEES;

--PREGUNTA 4: LENGTH DEVUELVE LA LONGITUD DE UNA CADENA
SELECT 
  LAST_NAME APELLIDO, 
  LENGTH(LAST_NAME) "LONGITUD APELLIDO" 
FROM EMPLOYEES WHERE 
  LAST_NAME LIKE 'A%' 
  OR LAST_NAME LIKE'M%' 
  OR LAST_NAME LIKE'J%'
ORDER BY 1;

--PREGUNTA 5: CEIL REDONDEA HACIA ARRIBA
SELECT 
  LAST_NAME APELLIDO,
  HIRE_DATE "FECHA CONTRATO",
  SYSDATE "FECHA ACTUAL",
  CEIL(MONTHS_BETWEEN (SYSDATE, HIRE_DATE  )) "MONTHS_WORKED" 
FROM EMPLOYEES ORDER BY 2;

--PREGUNTA 6: EL || CONCATENA
SELECT (LAST_NAME || ' EARNS ' || SALARY || ' MONTHLY BUT WANTS ' || 3*SALARY) 
AS "DREAM SALARY" FROM EMPLOYEES;

--PREGUNTA 7: LPAD RELLENO CARACTERES
SELECT LPAD(TO_CHAR(SALARY),15,'$') SALARY FROM EMPLOYEES;


--PREGUNTA 8: USE TO CHAR PARA DAR FORMATOS, DDSPTH ES PARA DIA EN CARDINAL
SELECT TO_CHAR(NEXT_DAY(ADD_MONTHS(HIRE_DATE,6),'LUNES'),'DAY, DDSPTH MONTH, YYYY') 
REVIEW FROM EMPLOYEES ORDER BY HIRE_DATE;

--PREGUNTA 9: REVISAR LOS CASE
SELECT LAST_NAME APELLIDO, HIRE_DATE FECHA, TO_CHAR(HIRE_DATE,'DAY') DAY FROM EMPLOYEES
ORDER BY (CASE TO_NUMBER(TO_CHAR(HIRE_DATE,'D')) 
WHEN 1 THEN 8 ELSE TO_NUMBER(TO_CHAR(HIRE_DATE,'D')) END);

--PREGUNTA 10
SELECT LAST_NAME APELLIDO, CASE WHEN COMMISSION_PCT IS NULL THEN 'NO COMMISSION'
ELSE '0' || TO_CHAR(COMMISSION_PCT) END AS COMISION FROM EMPLOYEES;

--PREGUNTA 11
SELECT LAST_NAME APELLIDO,SALARY, LPAD(' ',SALARY/1000+1,'*') FROM EMPLOYEES;


