--PRACTICA 4
--PREGUNTA 1 
SELECT E.LAST_NAME APELLIDO, 
       D.DEPARTMENT_ID "NUMERO DEPARTAMENTO", 
       d.department_name "NOMBRE DEPARTAMENTO" 
FROM EMPLOYEES E JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID); 

--PREGUNTA 2
SELECT 
  DISTINCT E.JOB_ID CARGO,
  D.DEPARTMENT_ID "ID DEPARTAMENTO",
  D.LOCATION_ID LOCALIZACION
FROM EMPLOYEES E JOIN DEPARTMENTS D ON (D.DEPARTMENT_ID = E.DEPARTMENT_ID) 
WHERE d.department_id = 80;

--PREGUNTA 3 APELLIDO EMPLEADO NOMBRE DE DEPARTAMENTO UBICACION CIUDAD 
--DE TODOS LOS EMPLEADOS QUE PERCIBEN COMISION
SELECT 
  E.LAST_NAME APELLIDO,
  D.DEPARTMENT_NAME "NOMBRE DEPARTAMENTO",
  D.LOCATION_ID LOCALIZACION,
  L.CITY CIUDAD
FROM EMPLOYEES E, departments D, LOCATIONS L 
WHERE D.LOCATION_ID = L.LOCATION_ID AND E.COMMISSION_PCT IS NOT NULL;
  
--PREGUNTA 4 TODOS LOS QUE TENGAN UNA a EN EL NOMBRE
SELECT 
  E.LAST_NAME, 
  D.DEPARTMENT_NAME  
FROM EMPLOYEES E, departments D WHERE 
  LAST_NAME LIKE '%a%' 
  AND E.DEPARTMENT_ID = D.DEPARTMENT_ID;
  
--PREGUNTA 5 TODA LA GENTE QUE TRABAJA EN TORONTO
SELECT
  e.LAST_NAME,
  e.JOB_ID,
  E.PHONE_NUMBER,
  D.DEPARTMENT_NAME,
  L.CITY
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L WHERE
  E.DEPARTMENT_ID = D.DEPARTMENT_ID
  AND D.LOCATION_ID = L.LOCATION_ID 
  AND L.CITY = 'Toronto';
  
--PREGUNTA 6
SELECT
  E.LAST_NAME||' '||e.first_name "NOMBRE EMPLEADO",
  E.EMPLOYEE_ID, E2.LAST_NAME, E2.EMPLOYEE_ID 
FROM EMPLOYEES E LEFT JOIN EMPLOYEES E2 ON E.MANAGER_ID = E2.EMPLOYEE_ID 
ORDER BY E.EMPLOYEE_ID;

--PREGUNTA 8
SELECT
  E.LAST_NAME "NOMBRE EMPLEADO",
  E1.LAST_NAME SOCIO,
  E1.DEPARTMENT_ID "NUMERO DEPARTAMENTO" 
FROM EMPLOYEES E INNER JOIN EMPLOYEES E1 
ON(e.department_id = e1.department_id)
WHERE E.LAST_NAME = 'Abel' AND E1.LAST_NAME <> 'Abel';


SELECT LAST_NAME FROM EMPLOYEES WHERE department_id = 80;

SELECT * FROM JOBS;


--PREGUNTA 10
SELECT 
    E.LAST_NAME APELLIDO, 
    E.HIRE_DATE "FECHA CONTRATO" 
FROM EMPLOYEES D JOIN EMPLOYEES E ON (E.HIRE_DATE > D.HIRE_DATE  AND D.LAST_NAME = 'Davies') 
ORDER BY E.HIRE_DATE;

--PREGUNTA 11
SELECT         
    E.LAST_NAME Employee,
    E.HIRE_DATE "Emp Hired",
    E2.LAST_NAME Manager,
    E2.HIRE_DATE "Mrg Hired"
FROM EMPLOYEES E JOIN EMPLOYEES E2 ON (E.MANAGER_ID = E2.EMPLOYEE_ID)
AND E.HIRE_DATE < E2.HIRE_DATE
ORDER BY E2.LAST_NAME;



  

