--pregunta 1 
SELECT employee_id, last_name, salARY * 12 "ANNUAL SALARY" FROM employees;

--PREGUNTA 2
SELECT * FROM DEPARTMENTS;

--PREGUNTA 3
SELECT  EMPLOYEE_ID "NUMERO DE EMPLEADO", LAST_NAME, JOB_ID, HIRE_DATE FROM EMPLOYEES;

--PREGUNTA 4
SELECT DISTINCT EMPLOYEE_ID FROM EMPLOYEES;

--PREGUNTA 7
SELECT LAST_NAME || ', ' || JOB_ID "EMPLOYEE AND TITTLE" FROM EMPLOYEES;
