--PREGUNTA 1
SELECT LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY > 12000;

--PREGUNTA 2
SELECT LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 176;

--PREGUNTA 3
SELECT LAST_NAME, SALARY FROM EMPLOYEES 
WHERE SALARY NOT BETWEEN 5000 AND 12000;

--PREGUNTA 4
SELECT LAST_NAME, JOB_ID, HIRE_DATE FROM EMPLOYEES 
WHERE HIRE_DATE BETWEEN '20/02/01' AND '01/05/03'
ORDER BY HIRE_DATE;

--PREGUNTA 5
SELECT LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES 
WHERE DEPARTMENT_ID = 20 OR DEPARTMENT_ID = 50 
ORDER BY LAST_NAME;

--PREGUNTA 6
SELECT LAST_NAME EMPLOYEE, SALARY "MONTHLY SALARY" FROM EMPLOYEES 
WHERE DEPARTMENT_ID = 20 OR DEPARTMENT_ID = 50 
AND SALARY BETWEEN 5000 AND 12000 ORDER BY LAST_NAME;

--PREGUNTA 7
SELECT LAST_NAME, HIRE_DATE FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '01/01/03' AND '31/12/03';

--PREGUNTA 8
SELECT LAST_NAME, SALARY FROM EMPLOYEES 
WHERE MANAGER_ID IS NULL;

--PREGUNTA 9
SELECT LAST_NAME, SALARY, COMMISSION_PCT FROM EMPLOYEES 
WHERE COMMISSION_PCT IS NOT NULL ORDER BY SALARY,COMMISSION_PCT;

--PREGUNTA 10
SELECT LAST_NAME FROM EMPLOYEES 
WHERE LAST_NAME LIKE '__a%';

